from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any

from .models import (
    ModelStatus,
    PredictionRequest,
    PredictionResponse,
)
from .registry import ModelRegistry


ModelExecutor = Callable[[Mapping[str, float]], float]


class MLInferenceEngine:
    """
    Production inference boundary for Layer 10 ML models.

    The engine resolves a deployed model from the registry, validates
    the incoming feature vector against the registered model contract,
    executes the supplied model executor, and returns a fully
    traceable PredictionResponse.
    """

    def __init__(
        self,
        registry: ModelRegistry,
        executors: Mapping[tuple[str, str], ModelExecutor] | None = None,
    ) -> None:
        if not isinstance(registry, ModelRegistry):
            raise TypeError("registry must be a ModelRegistry")

        self.registry = registry
        self._executors: dict[
            tuple[str, str],
            ModelExecutor,
        ] = dict(executors or {})

    def register_executor(
        self,
        model_id: str,
        model_version: str,
        executor: ModelExecutor,
    ) -> None:
        if not model_id.strip():
            raise ValueError("model_id is required")

        if not model_version.strip():
            raise ValueError("model_version is required")

        if not callable(executor):
            raise TypeError("executor must be callable")

        key = (model_id, model_version)

        if key in self._executors:
            raise ValueError(
                f"executor already registered: "
                f"{model_id}:{model_version}"
            )

        self._executors[key] = executor

    def predict(
        self,
        request: PredictionRequest,
        *,
        confidence: float = 1.0,
    ) -> PredictionResponse:

        if not isinstance(request, PredictionRequest):
            raise TypeError(
                "request must be a PredictionRequest"
            )

        if not 0.0 <= confidence <= 1.0:
            raise ValueError(
                "confidence must be between 0 and 1"
            )

        model = self.registry.get(
            request.model_id,
            request.model_version,
        )

        if model.status != ModelStatus.DEPLOYED:
            raise ValueError(
                "inference requires a deployed model"
            )

        self._validate_features(
            request,
            model.feature_names,
        )

        executor = self._executors.get(
            (
                request.model_id,
                request.model_version,
            )
        )

        if executor is None:
            raise LookupError(
                f"no executor registered for "
                f"{request.model_id}:{request.model_version}"
            )

        value = executor(request.features)

        if not isinstance(value, (int, float)):
            raise TypeError(
                "model executor must return a numeric value"
            )

        value = float(value)

        if not float("-inf") < value < float("inf"):
            raise ValueError(
                "model prediction must be finite"
            )

        return PredictionResponse(
            request_id=request.request_id,
            entity_id=request.entity_id,
            model_id=model.model_id,
            model_version=model.version,
            value=value,
            confidence=confidence,
            feature_version=model.feature_version,
            dataset_version=model.dataset_version,
            training_run_id=model.training_run_id,
            signal_ids=request.signal_ids,
            evidence_ids=request.evidence_ids,
            explanation=(
                f"Prediction generated by deployed model "
                f"{model.model_id}:{model.version} using "
                f"{len(model.feature_names)} registered features."
            ),
            metadata={
                "task_type": model.task_type.value,
                "model_type": model.model_type.value,
            },
        )

    @staticmethod
    def _validate_features(
        request: PredictionRequest,
        required_features: tuple[str, ...],
    ) -> None:
        supplied = set(request.features)
        required = set(required_features)

        missing = tuple(
            sorted(required - supplied)
        )

        unexpected = tuple(
            sorted(supplied - required)
        )

        if missing:
            raise ValueError(
                "missing required features: "
                + ", ".join(missing)
            )

        if unexpected:
            raise ValueError(
                "unexpected features: "
                + ", ".join(unexpected)
            )


def predict(
    registry: ModelRegistry,
    request: PredictionRequest,
    executor: ModelExecutor,
    *,
    confidence: float = 1.0,
) -> PredictionResponse:
    """
    Convenience inference function for a single model executor.
    """

    engine = MLInferenceEngine(registry)

    engine.register_executor(
        request.model_id,
        request.model_version,
        executor,
    )

    return engine.predict(
        request,
        confidence=confidence,
    )


__all__ = [
    "MLInferenceEngine",
    "ModelExecutor",
    "predict",
]
